// Code generated by MockGen. DO NOT EDIT.
// Source: assignment.go
//
// Generated by this command:
//
//	mockgen -source=assignment.go -package=hmntsk -destination=assignment_mock_test.go -typed
//

// Package hmntsk is a generated GoMock package.
package hmntsk

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGroupResolver is a mock of GroupResolver interface.
type MockGroupResolver struct {
	ctrl     *gomock.Controller
	recorder *MockGroupResolverMockRecorder
	isgomock struct{}
}

// MockGroupResolverMockRecorder is the mock recorder for MockGroupResolver.
type MockGroupResolverMockRecorder struct {
	mock *MockGroupResolver
}

// NewMockGroupResolver creates a new mock instance.
func NewMockGroupResolver(ctrl *gomock.Controller) *MockGroupResolver {
	mock := &MockGroupResolver{ctrl: ctrl}
	mock.recorder = &MockGroupResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupResolver) EXPECT() *MockGroupResolverMockRecorder {
	return m.recorder
}

// GroupsOf mocks base method.
func (m *MockGroupResolver) GroupsOf(ctx context.Context, actor string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GroupsOf", ctx, actor)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GroupsOf indicates an expected call of GroupsOf.
func (mr *MockGroupResolverMockRecorder) GroupsOf(ctx, actor any) *MockGroupResolverGroupsOfCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupsOf", reflect.TypeOf((*MockGroupResolver)(nil).GroupsOf), ctx, actor)
	return &MockGroupResolverGroupsOfCall{Call: call}
}

// MockGroupResolverGroupsOfCall wrap *gomock.Call
type MockGroupResolverGroupsOfCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGroupResolverGroupsOfCall) Return(arg0 []string, arg1 error) *MockGroupResolverGroupsOfCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGroupResolverGroupsOfCall) Do(f func(context.Context, string) ([]string, error)) *MockGroupResolverGroupsOfCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGroupResolverGroupsOfCall) DoAndReturn(f func(context.Context, string) ([]string, error)) *MockGroupResolverGroupsOfCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MembersOf mocks base method.
func (m *MockGroupResolver) MembersOf(ctx context.Context, group string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MembersOf", ctx, group)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MembersOf indicates an expected call of MembersOf.
func (mr *MockGroupResolverMockRecorder) MembersOf(ctx, group any) *MockGroupResolverMembersOfCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MembersOf", reflect.TypeOf((*MockGroupResolver)(nil).MembersOf), ctx, group)
	return &MockGroupResolverMembersOfCall{Call: call}
}

// MockGroupResolverMembersOfCall wrap *gomock.Call
type MockGroupResolverMembersOfCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGroupResolverMembersOfCall) Return(arg0 []string, arg1 error) *MockGroupResolverMembersOfCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGroupResolverMembersOfCall) Do(f func(context.Context, string) ([]string, error)) *MockGroupResolverMembersOfCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGroupResolverMembersOfCall) DoAndReturn(f func(context.Context, string) ([]string, error)) *MockGroupResolverMembersOfCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockAssignmentStrategy is a mock of AssignmentStrategy interface.
type MockAssignmentStrategy struct {
	ctrl     *gomock.Controller
	recorder *MockAssignmentStrategyMockRecorder
	isgomock struct{}
}

// MockAssignmentStrategyMockRecorder is the mock recorder for MockAssignmentStrategy.
type MockAssignmentStrategyMockRecorder struct {
	mock *MockAssignmentStrategy
}

// NewMockAssignmentStrategy creates a new mock instance.
func NewMockAssignmentStrategy(ctrl *gomock.Controller) *MockAssignmentStrategy {
	mock := &MockAssignmentStrategy{ctrl: ctrl}
	mock.recorder = &MockAssignmentStrategyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssignmentStrategy) EXPECT() *MockAssignmentStrategyMockRecorder {
	return m.recorder
}

// Assign mocks base method.
func (m *MockAssignmentStrategy) Assign(ctx context.Context, task Task, eligible []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Assign", ctx, task, eligible)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Assign indicates an expected call of Assign.
func (mr *MockAssignmentStrategyMockRecorder) Assign(ctx, task, eligible any) *MockAssignmentStrategyAssignCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assign", reflect.TypeOf((*MockAssignmentStrategy)(nil).Assign), ctx, task, eligible)
	return &MockAssignmentStrategyAssignCall{Call: call}
}

// MockAssignmentStrategyAssignCall wrap *gomock.Call
type MockAssignmentStrategyAssignCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAssignmentStrategyAssignCall) Return(arg0 string, arg1 error) *MockAssignmentStrategyAssignCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAssignmentStrategyAssignCall) Do(f func(context.Context, Task, []string) (string, error)) *MockAssignmentStrategyAssignCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAssignmentStrategyAssignCall) DoAndReturn(f func(context.Context, Task, []string) (string, error)) *MockAssignmentStrategyAssignCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
